config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.1.1
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/jenkins-docs/simple-java-maven-app:
      branch: master
      repo: https://github.com/jenkins-docs/simple-java-maven-app
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/jenkins-docs/simple-java-maven-app git:
        commands:
        - /usr/bin/env sh .sqa/script.jumpy-peach-lion.sh
        container: qc.acc_stealthy-white-ragdoll
  QC.Doc:
    repos:
      github.com/jenkins-docs/simple-java-maven-app find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.tasty-cinnamon-newt.sh
        container: qc.doc_messy-sepia-manatee
      github.com/jenkins-docs/simple-java-maven-app git:
        commands:
        - /usr/bin/env sh .sqa/script.tasty-tangerine-toad.sh
        container: qc.doc_stinky-wisteria-rabbit
      github.com/jenkins-docs/simple-java-maven-app markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.leaky-harlequin-audemer.sh
        container: qc.doc_homey-copper-earwig
  QC.Lic:
    repos:
      github.com/jenkins-docs/simple-java-maven-app licensee:
        commands:
        - /usr/bin/env sh .sqa/script.sleazy-cyan-oriole.sh
        container: qc.lic_shabby-azure-weasel
  QC.Sty:
    repos:
      github.com/jenkins-docs/simple-java-maven-app checkstyle:
        commands:
        - /usr/bin/env sh .sqa/script.leaky-lavender-fousek.sh
        container: qc.sty_greasy-vermilion-magpie
  QC.Ver:
    repos:
      github.com/jenkins-docs/simple-java-maven-app get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.blurry-aquamarine-catfish.sh
        container: qc.ver_pokey-grey-wolf
timeout: 5400
